version: '3.1'

services:
  app:
    container_name: expo-chat-manager
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    command: npm run dev
